In [1]:
!pip install pandas
import pandas as pd
df = pd.read_csv("./signed.csv", parse_dates=True)
!pip install protobuf==3.19.6
!pip install tensorflow-gpu==1.4.0

You are using pip version 10.0.1, however version 20.3.4 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


You are using pip version 10.0.1, however version 20.3.4 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


You are using pip version 10.0.1, however version 20.3.4 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [2]:
import tensorflow as tf
tf.__version__
tf.Session(config=tf.ConfigProto(log_device_placement=True))

C:\ProgramData\anaconda3-64\envs\pytorch_env\lib\site-packages\tensorflow\python\framework\dtypes.py:469: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\ProgramData\anaconda3-64\envs\pytorch_env\lib\site-packages\tensorflow\python\framework\dtypes.py:470: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\ProgramData\anaconda3-64\envs\pytorch_env\lib\site-packages\tensorflow\python\framework\dtypes.py:471: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\ProgramData\anaconda3-64\envs\pytorch_env\l

In [3]:
!pip install gensim
from gensim.models import Word2Vec
import time

sentences = []
for i in range(df.shape[0]):
    sentences.append(df['Text'].iloc[i].split(' '))
start = time.time()
model = Word2Vec(sentences=sentences, size=50, window=5, min_count=1, workers=20)
model.save("word2vec.model")
end = time.time()
print(end - start)

You are using pip version 10.0.1, however version 20.3.4 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.


115.66809058189392


In [4]:
print(model.wv.most_similar('газ'))

[('нефт', 0.8420153260231018), ('энергоресурс', 0.8008077144622803), ('топлив', 0.795139729976654), ('электроэнерг', 0.7877031564712524), ('энергоносител', 0.7808429598808289), ('нефтепродукт', 0.7499064207077026), ('спг', 0.745295524597168), ('пхг', 0.7434237003326416), ('газов', 0.7384294271469116), ('газа»', 0.7090457677841187)]


In [5]:
vectors = []
for text in df['Text']:
    vectors.append([model.wv[w] for w in text.split(' ')])

In [6]:
import numpy as np
import tensorflow as tf

X = vectors
y = np.zeros((len(vectors), 3))
classes = [-1, 0, 1]
for i in range(len(vectors)):
    y[i, classes.index(df['ChangeSign'].iloc[i])] = 1

In [7]:
count = int(len(vectors) * 0.8)
trainX, testX = X[:count], X[count:]
trainY, testY = y[:count], y[count:]

In [9]:
# Creates a session with log_device_placement set to True.
with tf.device("/job:localhost/replica:0/task:0/device:CPU:0"):
    a = tf.get_variable("a9", shape=[10000, 10000], initializer=tf.zeros_initializer)
    b = tf.get_variable("b9", shape=[10000, 10000], initializer=tf.zeros_initializer)
    c = tf.matmul(a, b, name="c1")
    print(a.device)
    print(c.device)
    
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print("here")
    start = time.time()
    print(sess.run(c))
    end = time.time()
    print(end - start)

/job:localhost/replica:0/task:0/device:CPU:0
/job:localhost/replica:0/task:0/device:CPU:0
here
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
4.954330682754517
